// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kiyrtjzwgtqzmkthlkig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpeXJ0anp3Z3Rxem1rdGhsa2lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MDMxMTksImV4cCI6MjA1ODE3OTExOX0.iBB6MDnvCBXCEbncrQmqn2HyQ74mnVvAhr9JDKyJyLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);